name: Node.js CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]  # Update with actual supported Node.js versions

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      working-directory: Ch02/02_03_ci_for_javascript
      
    - name: Build
      run: npm run build --if-present
      working-directory: Ch02/02_03_ci_for_javascript
      
    - name: Test
      run: npm test
      working-directory: Ch02/02_03_ci_for_javascript
